name: empoverty
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0' # Updated Dart SDK version

dependencies:
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  flutter_tts: ^3.0.0
  sms_autofill: ^2.0.0
  pin_code_fields: ^8.0.1
  intl_phone_number_input: ^0.7.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_maps_flutter: ^2.0.10
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.9

flutter:
  uses-material-design: true

assets:
  - assets/horse.png
