// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWj3Muy2nY3DSvAVORTjiAjPY3dtcyFZs',
    appId: '1:696133744789:web:295b1134e1e9253791c39c',
    messagingSenderId: '696133744789',
    projectId: 'empoverty-27c52',
    authDomain: 'empoverty-27c52.firebaseapp.com',
    storageBucket: 'empoverty-27c52.appspot.com',
    measurementId: 'G-GQBFMMSPX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC0OVuulkgTPO9PLMnUnZQ7K2l4zXxjv8',
    appId: '1:696133744789:android:540d3fac20941f0791c39c',
    messagingSenderId: '696133744789',
    projectId: 'empoverty-27c52',
    storageBucket: 'empoverty-27c52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5hjmTT_YyoWH3Tcwicn7v3LIAWztaz1U',
    appId: '1:696133744789:ios:16012422816f444391c39c',
    messagingSenderId: '696133744789',
    projectId: 'empoverty-27c52',
    storageBucket: 'empoverty-27c52.appspot.com',
    iosBundleId: 'com.empoverty.empoverty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5hjmTT_YyoWH3Tcwicn7v3LIAWztaz1U',
    appId: '1:696133744789:ios:1781bd2518e91bad91c39c',
    messagingSenderId: '696133744789',
    projectId: 'empoverty-27c52',
    storageBucket: 'empoverty-27c52.appspot.com',
    iosBundleId: 'com.example.empoverty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWj3Muy2nY3DSvAVORTjiAjPY3dtcyFZs',
    appId: '1:696133744789:web:4dd4ad52a7cc6ba991c39c',
    messagingSenderId: '696133744789',
    projectId: 'empoverty-27c52',
    authDomain: 'empoverty-27c52.firebaseapp.com',
    storageBucket: 'empoverty-27c52.appspot.com',
    measurementId: 'G-7PKF33R5FM',
  );

}